In [30]:
''' Implement FarthestFirstTraversal '''

def EuclidianDistance(pointA,Centers):
    import math
    ''' find the euclidian distance between point A and B in a m dimensional space
    INPUT:
    pointA=[0,0]
    Centers=[[5.0,5.0],[0.0,5.0],[1.0,1.0],[2.0,2.0],[3.0,3.0],[1.0,2.0]]
    OUTPUT= 1.41421356237
    '''
    return min([math.sqrt(sum([(pointA[m]-pointB[m])**2 for m in range(len(pointA))]))for pointB in Centers])



pointA=[0,0]
Centers=[[5.0,5.0],[0.0,5.0],[1.0,1.0],[2.0,2.0],[3.0,3.0],[1.0,2.0]]
#print EuclidianDistance(pointA,Centers)


def FarthestFirstTraversal(DataPoints, k):
    
    ''' 
    Find k centers minimizing the maximum distance between these data points and centers.
    INPUT:
    DataPoints=[[0.0,0.0],[5.0,5.0],[0.0,5.0],[1.0,1.0],[2.0,2.0],[3.0,3.0],[1.0,2.0]] #  a set of points Data in m-dimensional space (m=len(Datapoint[0]).
    k=3 # number of centers to find
    OUTPUT= [[0.0, 0.0], [5.0, 5.0], [0.0, 5.0]]
    '''
    
    def EuclidianDistance(pointA,Centers):
        import math
        ''' find the euclidian distance between point A and B in a m dimensional space
        INPUT:
        pointA=[0,0]
        Centers=[[5.0,5.0],[0.0,5.0],[1.0,1.0],[2.0,2.0],[3.0,3.0],[1.0,2.0]]
        OUTPUT= 1.41421356237
        '''
        return min([math.sqrt(sum([(pointA[m]-pointB[m])**2 for m in range(len(pointA))]))for pointB in Centers])

    ##################################################################################
    FirstCenter=DataPoints[0]
    print FirstCenter
    Centers=[FirstCenter]
    #print Centers
    while len(Centers) < k:
        maxdist=0
        NewCenter=[]
        for point in DataPoints[:]:
            print 'point',point, 'Centers',Centers
            dist=EuclidianDistance(point,Centers)
            print dist
            if dist > maxdist:
                print '!!!',point, dist
                NewCenter=point
                maxdist=dist   
                #print 'centers+1',Centers
                #print len(Centers)
        Centers+=[NewCenter]
        
    return Centers


############ 



'''
k=3
m=2
DataPoints=[[0.0,0.0],[5.0,5.0],[0.0,5.0],[1.0,1.0],[2.0,2.0],[3.0,3.0],[1.0,2.0]]


'''
f=open('input.txt','r')
#f=open('../../Downloads/rosalind_ba8a.txt','r')
#f=open('../../Downloads/dataset_.txt','r')
lines=f.read().splitlines()
f.close()

#print lines[0]
k=int(lines[0].split(' ')[0])
m=lines[0].split(' ')[1]
DataPoints=[map(float,[item for item in line.split(' ')]) for line in lines[1:]]


#print DataPoints[0]
#print k,m

#print FarthestFirstTraversal(DataPoints, k)
#print [' '.join(map(str,[coord for coord in item])) for item in FarthestFirstTraversal(DataPoints, k)]
print '\n'.join([' '.join(map(str,[coord for coord in item])) for item in FarthestFirstTraversal(DataPoints, k)])


[0.8, 12.0, 17.5, 0.9, 7.2]
point [0.8, 12.0, 17.5, 0.9, 7.2] Centers [[0.8, 12.0, 17.5, 0.9, 7.2]]
0.0
point [14.3, 3.9, 6.8, 6.2, 6.8] Centers [[0.8, 12.0, 17.5, 0.9, 7.2]]
19.7636029104
!!! [14.3, 3.9, 6.8, 6.2, 6.8] 19.7636029104
point [7.6, 3.0, 2.0, 1.6, 6.2] Centers [[0.8, 12.0, 17.5, 0.9, 7.2]]
19.208852126
point [23.4, 9.9, 8.0, 11.9, 1.7] Centers [[0.8, 12.0, 17.5, 0.9, 7.2]]
27.5076353037
!!! [23.4, 9.9, 8.0, 11.9, 1.7] 27.5076353037
point [2.9, 9.4, 2.6, 17.9, 19.9] Centers [[0.8, 12.0, 17.5, 0.9, 7.2]]
26.1432591694
point [0.1, 14.9, 27.6, 2.6, 7.6] Centers [[0.8, 12.0, 17.5, 0.9, 7.2]]
10.6752049161
point [14.9, 13.1, 9.1, 8.3, 5.5] Centers [[0.8, 12.0, 17.5, 0.9, 7.2]]
18.1171189763
point [0.3, 8.9, 14.3, 8.3, 4.7] Centers [[0.8, 12.0, 17.5, 0.9, 7.2]]
9.00610903776
point [6.4, 5.7, 3.0, 3.8, 13.2] Centers [[0.8, 12.0, 17.5, 0.9, 7.2]]
18.0474374912
point [3.5, 2.2, 2.4, 12.4, 10.6] Centers [[0.8, 12.0, 17.5, 0.9, 7.2]]
21.7979356821
point [11.5, 6.2, 0.3, 4.5, 20.0] Cen

In [32]:
'''Distortion(Data,Centers) = (1/n) ∑all points DataPoint in Datad(DataPoint, Centers)2.'''

def Distortion(DataPoints,Centers):
    '''
     Given a set Data of n data points and a set Centers of k centers, the squared error distortion of Data and Centers, denoted Distortion(Data, Centers), is defined as the mean squared distance from each data point to its nearest center,
     
     
    '''
    def EuclidianDistance(pointA,Centers):
        import math
        ''' find the euclidian distance between point A and B in a m dimensional space
        INPUT:
        pointA=[0,0]
        Centers=[[5.0,5.0],[0.0,5.0],[1.0,1.0],[2.0,2.0],[3.0,3.0],[1.0,2.0]]
        OUTPUT= 1.41421356237
        '''
        return min([math.sqrt(sum([(pointA[m]-pointB[m])**2 for m in range(len(pointA))]))for pointB in Centers])
    return sum([EuclidianDistance(Point,Centers)**2 for Point in DataPoints])/len(DataPoints)

#####################################################################

#f=open('input.txt','r')
f=open('../../Downloads/rosalind_ba8b.txt','r')
lines=f.read().splitlines()
f.close()

#print lines[0]
k=int(lines[0].split(' ')[0])
m=lines[0].split(' ')[1]
Data=[]
for n in range(len(lines)):
    line=lines[n]
    if line[0]=='-':
        break
Centers=[map(float,[item for item in line.split(' ')]) for line in lines[1:n]]        
DataPoints=[map(float,[item for item in line.split(' ')]) for line in lines[n+1:]]


print Distortion(DataPoints,Centers)

35.7262341463


In [115]:
'''LLoyd Algorithm'''

def EuclidianDistance(pointA,Centers):
        import math
        ''' find the euclidian distance between point A and B in a m dimensional space
        INPUT:
        pointA=[0,0]
        Centers=[[5.0,5.0],[0.0,5.0],[1.0,1.0],[2.0,2.0],[3.0,3.0],[1.0,2.0]]
        OUTPUT= 1.41421356237
        '''
        return min([math.sqrt(sum([(pointA[m]-pointB[m])**2 for m in range(len(pointA))]))for pointB in Centers])
    
def CenterOfGravity(Points):
    return [sum([point[m] for point in Points])/len(Points) for m in range(len(Points[0]))]
    
###################

#f=open('input.txt','r')
f=open('../../Downloads/rosalind_ba8c.txt','r')
lines=f.read().splitlines()
f.close()

#print lines[0]
k=int(lines[0].split(' ')[0])
m=lines[0].split(' ')[1]
DataPoints=[map(float,[item for item in line.split(' ')]) for line in lines[1:]]

#init
#print 'Centers',Centers
def Lloyd_algorithm(DataPoints):
    
    def EuclidianDistance(pointA,Centers):
        import math
        ''' find the euclidian distance between point A and B in a m dimensional space
        INPUT:
        pointA=[0,0]
        Centers=[[5.0,5.0],[0.0,5.0],[1.0,1.0],[2.0,2.0],[3.0,3.0],[1.0,2.0]]
        OUTPUT= 1.41421356237
        '''
        return min([math.sqrt(sum([(pointA[m]-pointB[m])**2 for m in range(len(pointA))]))for pointB in Centers])
    
    def CenterOfGravity(Points):
        return [sum([point[m] for point in Points])/len(Points) for m in range(len(Points[0]))]

    Centers= DataPoints[:k]
    clouds_old=[]
    while True:
        #centers to clusters
        Center_dic={}
        for point in Centers:
            Center_dic[str(point)]=[]
        for Point in DataPoints:
            mindist=EuclidianDistance(Point,Centers)
            center=[pointB for pointB in Centers if EuclidianDistance(Point,[pointB])==mindist][0]
            Center_dic[str(center)]+=[Point]
        #Clusters to centers
        clouds_new=[]
        for point in Centers:
            cloud=Center_dic[str(point)]
            clouds_new+=[cloud]
            gravity= CenterOfGravity(cloud)
            Center_dic[str(gravity)] = Center_dic.pop(str(point))
        Centers=[map(float,point[1:-1].split(', ')) for point in Center_dic.keys()]
        if clouds_new != clouds_old:
            clouds_old=clouds_new
        else:
            return Centers
            break
        
    
print '\n'.join([' '.join(map(str,[coord for coord in item])) for item in Lloyd_algorithm(DataPoints)])

   

15.9755681818 6.60568181818 3.93579545455
4.34566210046 10.4447488584 5.43196347032
8.64615384615 19.4559440559 7.84895104895
16.8496 6.4176 13.668
5.23564356436 5.91287128713 16.8801980198
5.12082018927 2.92870662461 4.54637223975


In [259]:
''' Implement the Soft k-Means Clustering Algorithm'''
np.set_printoptions(suppress=True)
def SoftkMeansClustering(k,m,B,DataPoints):
    ''' Implement the Soft k-Means Clustering Algorithm
    
    INPUT:
    k= 2
    m= 2
    B= 2.7
    DataPoints= [[1.3, 1.1], [1.3, 0.2], [0.6, 2.8], [3.0, 3.2], 
    [1.2, 0.7], [1.4, 1.6], [1.2, 1.0], [1.2, 1.1], [0.6, 1.5], [1.8, 2.6], [1.2, 1.3], [1.2, 1.0], [0.0, 1.9]]
    OUTPUT=[[1.6621292077004175, 2.6231300925735663], [1.0754390250735666, 1.1478787337691199]]
    '''
    
    import math
    import numpy as np
    
    
    n=len(DataPoints)
    mat_DataPoints= np.array(DataPoints)

    #starts from randomly chosen centers (the first 3)
    Centers=DataPoints[:k]
    step=0
    while True:
        step1=time.time()
        #### Centers to Soft Clusters (E-step):
        HiddenMatrix=np.zeros((len(DataPoints),k))
        dMatrix=HiddenMatrix.copy()
        #assign each data point a “responsibility” value for each cluster
        for j in range(k):
            dMatrix[:,j]=np.exp(-B*np.sqrt(((mat_DataPoints - Centers[j])**2).sum(axis=1)))
        for j in range(k):
            HiddenMatrix[:,j]= dMatrix[:,j]/dMatrix.sum(axis=1)
        
        #print 'step1 took:','%f' % (time.time()-step1),'s'
        
        #### Soft Clusters to Centers (M-step):
        
        step2=time.time()
        
        NewCenters= [[sum(mat_DataPoints[:,i]*HiddenMatrix[:,j])/sum(HiddenMatrix[:,j]) for i in range(m)] for j in range(k)]
        
        #print NewCenters
        #break
        #print 'step2 took:','%f' % (time.time()-step2),'s'

        Centers=NewCenters
        step+=1
        if step ==100:
            return Centers
            break

            
###########################################################################################################################


#f=open('input.txt','r')
#f=open('input2.txt','r')
f=open('../../Downloads/rosalind_ba8d.txt','r')
lines=f.read().splitlines()
f.close()

k=int(lines[0].split(' ')[0])
m=int(lines[0].split(' ')[1])
B=float(lines[1])
DataPoints=[map(float,[item for item in line.split(' ')]) for line in lines[2:]]

#print 'k=',k
#print 'm=',m
#print 'B=',B
#print 'DataPoints=',DataPoints

start=time.time()
print '\n'.join([' '.join(map(str,['%.3f' % coord for coord in item])) for item in SoftkMeansClustering(k,m,B,DataPoints)])

print 'script took', time.time()-start, 's'

3.709 4.873 4.015
7.899 10.653 20.722
19.749 10.236 8.372
5.815 16.029 6.062
4.874 4.931 12.901
12.767 4.945 4.871
script took 0.995817899704 s


In [325]:
def UPGMA(D,n):
    
    '''
    INPUT:
    n = 4
    matrix = [[ 0 20 17 11]
     [20  0 20 13]
     [17 20  0 10]
     [11 13 10  0]]
     OUTPUT=defaultdict(<type 'list'>, {0: [[5, 7.0]], 1: [[6, 8.833333333333334]], 
     2: [[4, 5.0]], 3: [[4, 5.0]], 4: [[3, 5.0], [2, 5.0], [5, 2.0]], 
     5: [[4, 2.0], [0, 7.0], [6, 1.833333333333334]], 
     6: [[5, 1.833333333333334], [1, 8.833333333333334]]} # where dic[key] = node source
                                                          # dic value[0]= node sink
                                                          # dic value[1]= branch length
    '''
    import pandas as pd
    import numpy as np
    from collections import defaultdict
    Clusters=map(str,range(n+1)[1:])
    D[D == 0] = float('Nan')
    D = pd.DataFrame(D, index=Clusters, columns=Clusters)
    T=[]
    leaf_counter={}
    for node in Clusters:
        leaf_counter[node]=1
    while len(Clusters)>1:
        min_val=np.nanmin(D) #D.values.min()
        for x in Clusters:
            for y in Clusters:
                D[x][y]
                if D[x][y]==min_val:
                    C1,C2=x,y
                    continue
        Cnew=str(C1)+', '+str(C2)
        T+=[Cnew]
        leaf_counter[str(Cnew)]=leaf_counter[C1]+leaf_counter[C2]
        D[str(Cnew)]=(D[C1]*leaf_counter[C1]+D[C2]*leaf_counter[C2])/leaf_counter[str(Cnew)]
        D=D.append(D[str(Cnew)], ignore_index=False)
        D[Cnew][Cnew]=float('NaN')
        del D[C1]
        del D[C2]
        D=D[D.index != C1]
        D=D[D.index != C2]
        Clusters.remove(C1)
        Clusters.remove(C2)
        Clusters.append(Cnew)
    root=Clusters[0]

    return T



#f=open('input.txt','r')
#f=open('input2.txt','r')
f=open('../../Downloads/rosalind_ba8e.txt','r')
lines=f.read().splitlines()
f.close()
n=int(lines[0])
matrix=[map(float,line.split()) for line in lines[1:] ]
matrix=np.matrix(matrix)
matrix=matrix[:n,:n]
#print matrix

print '\n'.join([' '.join(item.split(', ')) for item in UPGMA(matrix,n)])


7 6
9 1
19 15
19 15 7 6
8 4
12 3
19 15 7 6 10
9 1 2
20 14
19 15 7 6 10 11
18 13
19 15 7 6 10 11 20 14
9 1 2 8 4
18 13 12 3
16 5
18 13 12 3 17
9 1 2 8 4 19 15 7 6 10 11 20 14
9 1 2 8 4 19 15 7 6 10 11 20 14 18 13 12 3 17
9 1 2 8 4 19 15 7 6 10 11 20 14 18 13 12 3 17 16 5


[[ 0.    0.74  0.85  0.54  0.83  0.92  0.89]
 [ 0.74  0.    1.59  1.35  1.2   1.48  1.55]
 [ 0.85  1.59  0.    0.63  1.13  0.69  0.73]
 [ 0.54  1.35  0.63  0.    0.66  0.43  0.88]
 [ 0.83  1.2   1.13  0.66  0.    0.72  0.55]
 [ 0.92  1.48  0.69  0.43  0.72  0.    0.8 ]
 [ 0.89  1.55  0.73  0.88  0.55  0.8   0.  ]]
[0, 1, 2, 3, 4, 5, 6]
[12]
