In [4]:

'''UPGMA(D, n) 
      
Clusters ← n single-element clusters labeled 1, ... , n
     
 construct a graph T with n isolated nodes labeled by single elements 1, ... , n
    for every node v in T 
        Age(v) ← 0
    while there is more than one cluster
        find the two closest clusters Ci and Cj
 
        merge Ci and Cj into a new cluster Cnew with |Ci| + |Cj| elements
        add a new node labeled by cluster Cnew to T
        connect node Cnew to Ci and Cj by directed edges
 
        Age(Cnew) ← DCi, Cj / 2
        remove the rows and columns of D corresponding to Ci and Cj

        remove Ci and Cj from Clusters

        add a row/column to D for Cnew by computing D(Cnew, C) for each C in Clusters
        add Cnew to Clusters
    root ← the node in T corresponding to the remaining cluster
    for each edge (v, w) in T
        length of (v, w) ← Age(v) - Age(w)
    return T'''

def UPGMA(D,n):
    
    '''
    INPUT:
    n = 4
    matrix = [[ 0 20 17 11]
     [20  0 20 13]
     [17 20  0 10]
     [11 13 10  0]]
     OUTPUT=defaultdict(<type 'list'>, {0: [[5, 7.0]], 1: [[6, 8.833333333333334]], 
     2: [[4, 5.0]], 3: [[4, 5.0]], 4: [[3, 5.0], [2, 5.0], [5, 2.0]], 
     5: [[4, 2.0], [0, 7.0], [6, 1.833333333333334]], 
     6: [[5, 1.833333333333334], [1, 8.833333333333334]]} # where dic[key] = node source
                                                          # dic value[0]= node sink
                                                          # dic value[1]= branch length
    '''
    import pandas as pd
    import numpy as np
    from collections import defaultdict
    Clusters=range(n)
    #Cnew_num=max(Clusters)
    Cnew=max(Clusters)#name of new node
    D[D == 0] = 9999999
    D = pd.DataFrame(D, index=Clusters, columns=Clusters)
    T=defaultdict(list)
    Age={}
    #cluster_to_number={}
    leaf_counter={}
    for node in Clusters:
        T[node]=[]
        Age[node]=0
        #cluster_to_number[node]=node
        leaf_counter[node]=1
    while len(Clusters)>1:
        D[D == np.nan] = 9999999
        min_val=D.values.min()
        for x in Clusters:
            for y in Clusters:
                D[x][y]
                if D[x][y]==min_val:
                    C1,C2=x,y
                    continue
        #Cnew_num+=1
        #Cnew=(C1,C2)
        #cluster_to_number[Cnew]=Cnew_num
        Cnew+=1
        leaf_counter[Cnew]=leaf_counter[C1]+leaf_counter[C2]
        Age[Cnew]=float(D[C1][C2])/2
        #T[Cnew]=[[cluster_to_number[C1],Age[Cnew]-Age[C1]],[cluster_to_number[C2],Age[Cnew]-Age[C2]]]
        #T[C1]+=[[cluster_to_number[Cnew],Age[Cnew]-Age[C1]]]
        #T[C2]+=[[cluster_to_number[Cnew],Age[Cnew]-Age[C2]]]
        T[Cnew]=[[C1,Age[Cnew]-Age[C1]],[C2,Age[Cnew]-Age[C2]]]
        T[C1]+=[[Cnew,Age[Cnew]-Age[C1]]]
        T[C2]+=[[Cnew,Age[Cnew]-Age[C2]]]
        D[Cnew]=(D[C1]*leaf_counter[C1]+D[C2]*leaf_counter[C2])/leaf_counter[Cnew]
        D=D.append(D[Cnew], ignore_index=False)
        D[Cnew][Cnew]=9999999
        del D[C1]
        del D[C2]
        D=D[D.index != C1]
        D=D[D.index != C2]
        Clusters.remove(C1)
        Clusters.remove(C2)
        Clusters.append(Cnew)
    root=Clusters[0]
    
    #for old_key in T.keys():
    #    T[old_key] = T.pop(old_key)
    return T


import numpy as np

f=open('input.txt','r')
#f=open('input2.txt','r')
#f=open('../../Downloads/dataset_10332_8.txt','r')
#f=open('../../Downloads/rosalind_ba7d.txt','r')
lines=f.read().splitlines()
f.close()
n=int(lines[0])
matrix=[map(int,line.split()) for line in lines[1:] ]
matrix=np.matrix(matrix)
matrix=matrix[:n,:n]
print 'n =',n
print 'matrix =',matrix

T= UPGMA(matrix,n)
print T

fa=open('output.txt','w')
fa.close()
for key in T.keys():
    #print 'len,',len(T[key])
    #print T[key]
    #print 'count',count_leaves(T[key])
    try:
        for item in T[key]:
            #print 'item',item
            entry= str(key)+'->'+str(item[0])+':'+str("%.3f" % item[1])
            print entry
            fa=open('output.txt','a')
            fa.write(entry+'\n')
            fa.close()
    except TypeError:
        #print key,T[key]
        entry= str(key)+'->'+str(T[key][0])+':'+str("%.3f" % T[key][1])
        print entry
        fa=open('output.txt','a')
        fa.write(entry+'\n')
        fa.close()
        



n = 4
matrix = [[ 0 20 17 11]
 [20  0 20 13]
 [17 20  0 10]
 [11 13 10  0]]
defaultdict(<type 'list'>, {0: [[5, 7.0]], 1: [[6, 8.833333333333334]], 2: [[4, 5.0]], 3: [[4, 5.0]], 4: [[3, 5.0], [2, 5.0], [5, 2.0]], 5: [[4, 2.0], [0, 7.0], [6, 1.833333333333334]], 6: [[5, 1.833333333333334], [1, 8.833333333333334]]})
0->5:7.000
1->6:8.833
2->4:5.000
3->4:5.000
4->3:5.000
4->2:5.000
4->5:2.000
5->4:2.000
5->0:7.000
5->6:1.833
6->5:1.833
6->1:8.833


In [4]:
'''NeighborJoining(D,n)
    if n = 2
        T ← tree consisting of a single edge of length D1,2
        return T
    D* ← neighbor-joining matrix constructed from the distance matrix D
    find elements i and j such that D*i,j is a minimum non-diagonal element of D*
    Δ ← (TotalDistanceD(i) - TotalDistanceD(j)) /(n - 2)
    limbLengthi ← (1/2)(Di,j + Δ)
    limbLengthj ← (1/2)(Di,j - Δ)
    add a new row/column m to D so that Dk,m = Dm,k = (1/2)(Dk,i + Dk,j - Di,j) for any k
    remove rows  i and j from D
    remove columns i and j from D
    T ← NeighborJoining(D, n - 1)
    add two new limbs (connecting node m with leaves i and j) to the tree T
    assign length limbLengthi to Limb(i)
    assign length limbLengthj to Limb(j)
    return T'''

def NeighborJoining(D,n):
    import numpy as np
    import pandas as pd
    from collections import defaultdict
    
    #add row and column names to pandas dataframe (for easy indexing of nodes/leaves)
    D = pd.DataFrame(D, index=D.index.values, columns=D.index.values)
    Cnew=max(D.index.values)+1 #define name of every new node
    
    # initialize graph with leaves
    T=defaultdict(list)
    for node in D.index.values:
        T[node]=[]
    
    #make tree consisting of a single edge of length D1,2 when two nodes
    if n == 2:
        print 'D',D
        id_0=D.index.values[0]
        id_1=D.index.values[1]
        T[id_0]=[[id_1,D[id_0][id_1]]]
        T[id_1]=[[id_0,D[id_1][id_0]]]
        return T
    
    # make D* (neighbor-joining matrix constructed from the distance matrix D) and find neighboring leaves
    D_star=np.zeros((n,n))
    D_star=pd.DataFrame(D_star, index=D.index.values,columns=D.index.values )
    total_dist={}
    min_val=0
    for x in D:
        total_dist[x]=D[x].sum()
    for i in D:
        for j in D:
            if i==j:
                pass
            else:
                value=(n-2)*D[i][j]-total_dist[i]-total_dist[j]
                D_star[i][j]= value
                if value < min_val:
                    min_val=value
                    I=i
                    J=j
                    delta= (total_dist[I]-total_dist[J])/(n-2)
                    limblen_i=(D[I][J]+delta)/2
                    limblen_j=(D[I][J]-delta)/2
    print 'i',I,'j',J,'limblen_i',limblen_i    
    print 'D_star',D_star
    #update matrix D
    D[Cnew]=(D[I] + D[J] - D[I][J])/2
    D=D.append(D[Cnew], ignore_index=False)
    D[Cnew][Cnew]=0
    del D[I]
    del D[J]
    D=D[D.index != I]
    D=D[D.index != J]
    print I,J,D
    # recursive
    T=  NeighborJoining(D, n - 1)
    
    # add leaves to node
    T[I]+=[[Cnew,limblen_i]]
    T[J]+=[[Cnew,limblen_j]]
    if Cnew in T.keys():
        T[Cnew]+=[[I,limblen_i],[J,limblen_j]]
    else:
        T[Cnew]=[[I,limblen_i],[J,limblen_j]]   
    return T



################# run function ##################

import numpy as np
import pandas as pd
#f=open('input.txt','r')
#f=open('input2.txt','r')
#f=open('../../Downloads/dataset_10333_7.txt','r')
#f=open('../../Downloads/rosalind_ba7e.txt','r')
#lines=f.read().splitlines()
#f.close()
#n=int(lines[0])
n=4
#matrix=[map(int,line.split()) for line in lines[1:] ]
#matrix= [[0,29,9,11],[29,0,17,11],[9,17,0,8],[11,11,8,0]]
#matrix= [[0,20,9,11],[20,0,17,11],[9,17,0,8],[11,11,8,0]]
matrix= [[0,14,17,17],[14,0,7,13],[17,7,0,16],[17,13,16,0]]
matrix=np.matrix(matrix)
matrix=matrix[:n,:n]
matrix=pd.DataFrame(matrix)
print matrix
T= NeighborJoining(matrix,n)
fa=open('output.txt','w')
fa.close()
for key in T.keys():
    for item in T[key]:
        entry= str(key)+'->'+str(item[0])+':'+str("%.3f" % item[1])
        print entry
        fa=open('output.txt','a')
        fa.write(entry+'\n')
        fa.close()
        

    0   1   2   3
0   0  14  17  17
1  14   0   7  13
2  17   7   0  16
3  17  13  16   0
i 0 j 3 limblen_i 9
D_star       0     1     2     3
0   0.0 -54.0 -54.0 -60.0
1 -54.0   0.0 -60.0 -54.0
2 -54.0 -60.0   0.0 -54.0
3 -60.0 -54.0 -54.0   0.0
0 3      1    2    4
1  0.0  7.0  5.0
2  7.0  0.0  8.0
4  5.0  8.0  0.0
i 1 j 2 limblen_i 2.0
D_star       1     2     4
1   0.0 -20.0 -20.0
2 -20.0   0.0 -20.0
4 -20.0 -20.0   0.0
1 2      4    5
4  0.0  3.0
5  3.0  0.0
D      4    5
4  0.0  3.0
5  3.0  0.0
0->4:9.000
1->5:2.000
2->5:5.000
3->4:8.000
4->5:3.000
4->0:9.000
4->3:8.000
5->4:3.000
5->1:2.000
5->2:5.000
