In [54]:
'''Distance Between Leaves Problem

Compute the distances between leaves in a weighted tree.

Given: An integer n followed by the adjacency list of a weighted tree with n leaves.

Return: A space-separated n x n (di, j), where di, j is the length of the path between leaves i and j.'''


def distances_between_leaves(n,adjacency_list):
    """    
    Distances Between Leaves Problem: Compute the distances between leaves in a weighted tree.
    Input:  An integer n followed by the adjacency list of a weighted tree with n leaves.
    Output: An n x n matrix (di,j), where di,j is the length of the path between leaves i and j.
    """
    import numpy as np
    adj = {}
    for (k, v, w) in adjacency_list:
        adj.setdefault(k,[]).append((v,w))
    #print 'adj',adj    
    # assume the keys are given from [0,....,p]
    #check if assumption is true
    assert min(adj.keys()) == 0 # assert [condition] tells the program to test that condition, and trigger an error if the condition is false
    assert max(adj.keys()) == len(adj.keys()) - 1
    
    #find out leaves
    leaves = [k for k,v in adj.iteritems() if len(v) == 1]
    assert len(leaves) == n
    #print leaves
    
    #make empty arrays with right size
    node_to_node_distance = np.zeros( (len(adj),len(adj)), dtype = int )
    #print 'node_to_node_distance',node_to_node_distance
    leaf_to_leaf_distance = np.zeros( (n,n), dtype = int )   
    #print 'leaf_to_leaf_distance',leaf_to_leaf_distance
    
    
    def dfs(path):
        import numpy as np
        for v,w in adj[path[-1][0]]:
            if visited[v] == True:
                continue
            visited[v] = True
            pathlen = path[-1][1] + w
            for (iv,ilen) in path:
                node_to_node_distance[iv,v] = pathlen - ilen
                node_to_node_distance[v,iv] = pathlen - ilen
            npath = path[:]
            npath.append((v,pathlen))
            dfs(npath)
            
            
    for leaf in leaves:
        visited = [None] * len(adj)
        visited[leaf] = True
        path = [(leaf,0)]
        #print 'path',path
        dfs(path)
        #print 'dfs path',dfs(path)
        #print 'node_to_node_distance',node_to_node_distance
    for i,m in enumerate(leaves):
        for j,n in enumerate(leaves):
            leaf_to_leaf_distance[i,j] = node_to_node_distance[m,n]
    return leaf_to_leaf_distance

#m = distances_between_leaves(4,[(0, 4, 11), (1, 4, 2), (2, 5, 6), (3, 5, 7), (4, 0, 11), (4, 1, 2), (4, 5, 4), (5, 4, 4), (5, 3, 7), (5, 2, 6)])
#res = np.array([[ 0, 13, 21, 22],[13,  0, 12, 13],[21, 12,  0, 13],[22, 13, 13,  0]])
#assert not (m != res).sum()



### test 1 ###


f=open('input.txt','r')
lines=f.read().splitlines()
f.close()
leaves=int(lines[0])
adj=lines[1:]


### test 3 ###

f=open('input.txt','r')
lines=f.read().splitlines()
f.close()
leaves=int(lines[0])
adj=lines[1:]


### challenge ###
'''
f=open('../../Downloads/rosalind_ba7a.txt','r')
lines=f.read().splitlines()
f.close()
leaves=int(lines[0])
adj=lines[1:]
'''
#####
import numpy as np
np.set_printoptions(threshold=np.inf)

adjency_list=[]
for item in adj:
    node=[[item.split('->')[0]]+[item.split('->')[1].split(':')[0]]+[item.split('->')[1].split(':')[1]]]
    node=[map(int,item) for item in node]
    adjency_list+=node

print adjency_list
#distances_between_leaves(leaves,adjency_list)
#print str(distances_between_leaves(leaves,adjency_list)).replace('[','').replace(']','')

#np.savetxt('test.out', distances_between_leaves(leaves,adjency_list), delimiter=' ',fmt='%1i')

IndexError: list index out of range

In [81]:
'''Code Challenge: Solve the Limb Length Problem.
     Input: An integer n, followed by an integer j between 0 and n - 1, followed by a space-separated
     additive distance matrix D (whose elements are integers).
     Output: The limb length of the leaf in Tree(D) corresponding to row j of this distance
     matrix (use 0-based indexing).'''

def LimbLength(j,matrix):
    import numpy as np
    limblength=[]
    done_pairs=[]
    for i in [x for x in xrange(n) if x != j]:
        for k in [x for x in xrange(n-1) if x != j and [x,i] not in done_pairs]:
            done_pairs+=[[i,k]]
            limblength+=[(matrix[i,j]+matrix[j,k]-matrix[i,k])/2]
    return min(limblength)

def Limb_Length(n,j,d):
    """
    CODE CHALLENGE: Solve the Limb Length Problem in linear time.
    Input: An integer n, followed by an integer j between 0 and n, followed by a space-separated
    additive distance matrix D (whose elements are integers).
    Output: The limb length of the leaf in Tree(D) corresponding to the j-th row of this distance
    matrix (use 0-based indexing).
    """
    assert n > 2
    assert d.shape == (n,n)
    i = (j+1) % n
    k = (j+2) % n
    minlen = (d[i,j] + d[j,k] - d[i,k])/2
    for k in range(n):
        if i==j or k==j:
            continue
        currlen = (d[i,j] + d[j,k] - d[i,k])/2
        minlen = min(minlen,currlen)
    return minlen

### Test 1,2, Challenge: worked ###

f=open('input.txt','r')
#f=open('../../Downloads/dataset_10329_11.txt','r')
#f=open('../../Downloads/rosalind_ba7b.txt','r')
lines=f.read().splitlines()
f.close()
#n=int(lines[0])
#j=int(lines[1])
j=2
n=4
matrix=[map(int,line.split(' ')) for line in lines[:] ]
matrix=np.matrix(matrix)
print n,j,matrix


print LimbLength(j,matrix)
print Limb_Length(n,j,matrix)

4 2 [[ 0 20  9 11]
 [20  0 17 11]
 [ 9 17  0  8]
 [11 11  8  0]]
3
3


In [6]:
'''AdditivePhylogeny(D, n)
    if n = 2
        return the tree consisting of a single edge of length D1,2
    limbLength ← Limb(D, n)
    for j ← 1 to n - 1
        Dj,n ← Dj,n - limbLength
        Dn,j ← Dj,n
    (i, k) ← two leaves such that Di,k = Di,n + Dn,k
    x ← Di,n
    remove row n and column n from D
    T ← AdditivePhylogeny(D, n - 1)
    v ← the (potentially new) node in T at distance x from i on the path between i and k
    add leaf n back to T by creating a limb (v, n) of length limbLength
    return T'''


def find_path(i,j,adj):
    visited = [None] * (max(adj.keys())+1)
    def dfs(path):
        for (v,w) in adj[path[-1][0]]:
            if visited[v] == True:
                continue
            visited[v] = True
            pathlen = path[-1][1] + w
            npath = path[:]                
            npath.append((v,pathlen))
            if (v == j):
                # found the node that ends path.
                return npath
            result = dfs(npath)
            if result is not None:
                return result
        return
    return dfs([(i,0)])

    
'''def LimbLength(j,matrix):
    import numpy as np
    limblength=[]
    done_pairs=[]
    for i in [x for x in xrange(n-1) if x != j]:
        for k in [x for x in xrange(n-1) if x != j and [x,i] not in done_pairs]:
            print i,k,j
            done_pairs+=[[i,k]]
            limblength+=[(matrix[i,j]+matrix[j,k]-matrix[i,k])/2]
    return min(limblength)'''

def LimbLength(n,j,d):
    """
    CODE CHALLENGE: Solve the Limb Length Problem in linear time.
    Input: An integer n, followed by an integer j between 0 and n, followed by a space-separated
    additive distance matrix D (whose elements are integers).
    Output: The limb length of the leaf in Tree(D) corresponding to the j-th row of this distance
    matrix (use 0-based indexing).
    """
    assert n > 2
    assert d.shape == (n,n)
    i = (j+1) % n
    k = (j+2) % n
    minlen = (d[i,j] + d[j,k] - d[i,k])/2
    for k in range(n):
        if i==j or k==j:
            continue
        currlen = (d[i,j] + d[j,k] - d[i,k])/2
        minlen = min(minlen,currlen)
    return minlen

def find_condition(d,j):
        # (i,l,k) ← three leaves such that
        # Di,k = Di,j + Dj,k
        # i < j < l
        for i in range(j):
            for k in range(i+1,j):
                if d[i,k] == d[i,j]+d[j,k]:
                    return (i,k)
        assert 0
        return
    
def add_leaf(j,i,k,lenij,limblen,tree):
    from collections import defaultdict
    
    path= find_path(i,k,tree)

    for x in range(len(path)-1):
        dist_before=path[x][1]
        dist_after=path[x+1][1]
        
        if dist_before<lenij and dist_after>lenij:
            nodein=path[x][0]
            len_nodeinj=lenij-dist_before
            nodeout=path[x+1][0]
            len_nodeoutj=dist_after-lenij

            new_node = max(tree.keys()+[n-1])+1 
            
            tree[nodein].remove([node for node in tree[nodein] if node[0]==nodeout][0])
            tree[nodeout].remove([node for node in tree[nodeout] if node[0]==nodein][0])

            tree[nodein].append([new_node,len_nodeinj])
            tree[new_node]=[[nodein,len_nodeinj]]

            tree[new_node].append([nodeout,len_nodeoutj])
            tree[nodeout].append([new_node,len_nodeoutj])

            tree[new_node].append([j,limblen])
            tree[j]=[[new_node,limblen]]
            break
        if dist_after==lenij:
            tree[nodeout].append(j,limblen)
            tree[j].append(nodeout,limblen)
            break
    return tree



    
def AdditivePhylogeny(matrix, n):
    import numpy as np
    from collections import defaultdict
    D=matrix[:]
    tree=defaultdict(list)
    if n == 2:
        
        tree[0]=[[1,D[0,1]]]
        tree[1]=[[0,D[1,0]]]
        return tree
    
    j=n-1
    limblen = LimbLength(n,j,D)

    Dbald=D[:]
    Dbald[j,:]=D[j,:]-limblen
    Dbald[:,j]=D[:,j]-limblen
    Dtrim=Dbald[:j,:j]
    
    (i,k)=find_condition(Dbald,j)
    (lenij,lenjk)=(Dbald[i,j], Dbald[j,k])
    
    T=AdditivePhylogeny(Dtrim, j)
    add_leaf(j,i,k,lenij,limblen,T)
    #print T
    return T


import numpy as np
#f=open('input.txt','r')
#f=open('input2.txt','r')
f=open('../../Downloads/dataset_10330_6.txt','r')
#f=open('../../Downloads/rosalind_ba7c.txt','r')
lines=f.read().splitlines()
f.close()
n=int(lines[0])
#print [line.split(' ') for line in lines[1:10] ]
matrix=[map(int,line.split(' ')) for line in lines[1:] ]
matrix=np.matrix(matrix)
matrix=matrix[:n,:n]
print n
#print matrix
#print n,j,matrix

T= AdditivePhylogeny(matrix, n)
fa=open('output.txt','w')
fa.close()
for key in T.keys():
    for item in T[key]:
        entry= str(key)+'->'+str(item[0])+':'+str(item[1])
        #print entry
        fa=open('output.txt','a')
        fa.write(entry+'\n')
        fa.close()

24
